method: onet_2d_cam
data:
#  path: /home/wenjing/storage/data/ShapeNet
  path: /home/wenjing/Downloads/ShapeNet
  img_folder: img_choy2016
  img_size: 224
  points_subsample: 128
  dim: 2
  classes: ['02828884']
  img_with_camera: true
#  with_transforms: true
model:
  encoder_latent: null
  decoder: cbatchnorm
#  decoder: simple
  encoder: resnet18
  c_dim: 256
  z_dim: 0
  z_resolution: 64
  attention: false
  positional_encoding: true
training:
#  out_dir:  /home/wenjing/storage/out/onet
  out_dir:  out/img/onet_2d
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
#  model_file: /home/wenjing/Desktop/onet_2d_64/model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 128
  upsampling_steps: 0
  generation_dir: pretrained
