method: conv_onet_2d
data:
#  path: /home/wenjing/storage/data/ShapeNet
  path: /home/wenjing/Downloads/ShapeNet2
  img_folder: img_choy2016
  img_size: 224
  points_subsample: 32
  dim: 2
  padding: 0.1
  classes: ['03001627']
model:
  encoder_latent: null
  decoder: simple_local
  encoder: unet
  c_dim: 32
  z_dim: 0
  z_resolution: 64
training:
#  out_dir:  /home/wenjing/storage/out/onet
  out_dir:  out/img/onet_2d
  batch_size: 32
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: /home/wenjing/Desktop/onet_2d_64/model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 128
  upsampling_steps: 0
  generation_dir: pretrained




#model:
#  encoder: pointnet_local_pool
#  encoder_kwargs:
#    hidden_dim: 32
#    plane_type: ['xz']
#    plane_resolution: 64
#    unet: True
#    unet_kwargs:
#      depth: 4
#      merge_mode: concat
#      start_filts: 32
#  decoder: simple_local
#  decoder_kwargs:
#    sample_mode: bilinear # bilinear / nearest
#    hidden_size: 32
#  c_dim: 32
#training:
#  out_dir: out/pointcloud/shapenet_1plane
#  batch_size: 32
#  model_selection_metric: iou
#  model_selection_mode: maximize
#  print_every: 1000
#  visualize_every: 10000
#  validate_every: 10000
#  checkpoint_every: 2000
#  backup_every: 10000
#  n_workers: 8
#  n_workers_val: 4

#generation:
#  vis_n_outputs: 2
#  refine: false
#  n_x: 128
#  n_z: 1
