method: onet_1d
data:
  path: /home/wenjing/storage/data/1d_ShapeNet/2d_ShapeNet
#  path: /home/wenjing/storage/data/ShapeNet
  img_folder: img_choy2016
  img_size: 224
  points_subsample: 128
  dim: 1
#  classes: ['03636649']
model:
  encoder_latent: null
  decoder: cbatchnorm_or
  encoder: resnet18
  c_dim: 256
  z_dim: 0
  yz_resolution: 64
  attention: false
  positional_encoding: false
training:
  out_dir:  /home/wenjing/storage/data2/onet_1d_32
#  out_dir:  out/img/onet_2d
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
#  model_file: /home/wenjing/storage/data2/onet_2d_32/model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32
  upsampling_steps: 0
  generation_dir: pretrained
