method: onet_2d
data:
  path: /home/wenjing/storage/data/ShapeNet
#  path: /home/wenjing/Downloads/ShapeNet
  img_folder: img_choy2016
  img_size: 224
  points_subsample: 1024
  dim: 2
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
  z_resolution: 32
training:
  out_dir:  /home/wenjing/storage/onet_2d
#  out_dir:  out/img/onet_2d
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
#  model_file: /home/wenjing/occupancy_networks-master/out/img/onet_2d/model.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32
  upsampling_steps: 2
  generation_dir: pretrained
