method: pix2mesh
data:
  multiclass: True
  path: /home/wenjing/storage/data/ShapeNet
  base_mesh: im2mesh/pix2mesh/ellipsoid/face3.obj
  ellipsoid: im2mesh/pix2mesh/ellipsoid/info_ellipsoid.dat
  img_folder: img_choy2016
  img_size: 224
  img_with_camera: true
  with_transforms: true
  pointcloud_target_n: 8000
model:
  encoder_latent2: simple
  decoder2: another
  encoder2: tensorflow
  encoder_kwargs2: {}
  decoder_kwargs2:
    adjust_ellipsoid: True
  hidden_dim2: 256
  feat_dim2: 963
  c_dim2: 512
  z_dim2: 64
  adjust_losses2: True
training:
  out_dir: /home/wenjing/storage/p2m
#  out_dir2: /home/wenjing/storage/onet
  batch_size: 1
  print_every: 40
  visualize_every: 10000
  checkpoint_every: 1000
  validate_every: 2000
  model_selection_metric: chamfer
test:
  threshold: 0.9
  eval_mesh: true
  eval_pointcloud: false
#  model_file: /home/wenjing/Desktop/pretrained_full2.pt
generation:
  batch_size: 100000
  generate_mesh: true
  generate_pointcloud: false
  generation_dir: pretrained
