inherit_from: configs/img/pixel2mesh.yaml
test:
  model_file: /home/wenjing/storage/freeze_en/model_best.pt
#  model_file: /home/wenjing/occupancy_networks-master/out/default/model_best.pt
#  model_file: /home/wenjing/Desktop/model_400000.pt
generation:
  generation_dir: pretrained