method: onet_2d_pointmap
data:
#  path: /home/wenjing/storage/data/ShapeNet
  path: /home/wenjing/Downloads/ShapeNet2
  img_folder: img_choy2016
  img_size: 224
  points_subsample: 127
  dim: 2
  padding: 0.1
  classes: ['03001627']
  img_with_camera: true
  with_transforms: true
model:
  encoder_latent: null
  decoder: simple_local
  encoder: resnet18_shared
#  c_dim_local: 0
  c_dim_local: 256
  c_dim_global: 0
  z_dim: 0
  z_resolution: 64
training:
#  out_dir:  /home/wenjing/storage/out/onet
  out_dir:  out/img/onet_2d
  load_dir: /home/wenjing/Desktop/oc_encoder.pt
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: /home/wenjing/Desktop/onet_2d_64/model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 128
  upsampling_steps: 0
  generation_dir: pretrained