method: psgn
data:
#  path: /home/wenjing/storage/data/ShapeNet
  path: /home/wenjing/Downloads/ShapeNet
  img_folder: img_choy2016
  img_size: 224 
  pointcloud_target_n: 1024
  classes: ['03001627']
model:
  decoder2: simple
  encoder2: resnet18
  c_dim: 256 
  z_dim: 0
training:
  out_dir: out/img/psgn
  batch_size: 64
test:
  eval_mesh: true
  eval_pointcloud: false
  model_file:  /home/wenjing/Desktop/model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  ################################
  generation_dir: pretrained
  generate_mesh: true
  generate_pointcloud: false
  #####################################
#  generate_mesh: false

