method: shared_2code
data:
  path: /home/wenjing/storage/data/2d_ShapeNet
#  path: /home/wenjing/storage/data/ShapeNet
  img_folder: img_choy2016
  img_size: 224
  points_subsample: 256
  dim: 2
  padding: 0.1
#  classes: ['03001627']
  img_with_camera: true
  with_transforms: true
model:
  encoder_latent: null
#  decoder: simple_local
  decoder: cbatchnorm_local
  encoder: resnet18_shared
#  c_dim_local: 0
  c_dim_global: 256
  c_dim_local: 32
  z_dim: 0
  z_resolution: 64
  normalize: true
training:
  out_dir:  /home/wenjing/storage/shared/res18_freeze_lastlocal_cbatch_gridsample2_nofreeze
  load_dir: /home/wenjing/storage/oc_encoder.pt
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 20000
  validate_every: 20000
test:
  threshold: 0.3
  eval_mesh: true
  eval_pointcloud: false
  model_file: /home/wenjing/storage/shared/res18_freeze_lastlocal_cbatch_gridsample2_nofreeze/model_best.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 64
  upsampling_steps: 0
  generation_dir: pretrained